apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: flm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: saivennelakota/app-library:appimagev1
          ports:
            - containerPort: 5000
