apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: flm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: saivennelakota/library-application:appimage-v2
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: library-app-config
            - secretRef:
                name: library-app-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
