apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: flm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: saivennelakota/app-library:dbimage
          ports:
            - containerPort: 3306
