apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: flm
spec:
  serviceName: db
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: db
          image: shaikmustafa/flm2026:dbimage
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: library-app-config
            - secretRef:
                name: library-app-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
              subPath: mysql

  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
